/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import android.security.keystore.KeyProperties
import java.security.KeyPairGenerator
import java.security.Signature
import java.security.interfaces.ECPrivateKey
import java.security.spec.*

class Library {
    fun someLibraryMethod(): Boolean {

        val generator: KeyPairGenerator =
                KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC)
        generator.initialize(ECGenParameterSpec("secp256r1"))
        val keyPair = generator.generateKeyPair()

        val sig = Signature.getInstance("SHA256withECDSA")
        sig.initSign(keyPair.private as ECPrivateKey)
        sig.update("Hello, World".toByteArray())
        return true
    }

    fun generateP256DerivedSeed() {}

    fun generateDomainSpecificKeys() {}

    fun signWithDomainSpecificKeys() {}
}
